<a href="https://colab.research.google.com/github/yoonhyunbin/pythonBDA/blob/main/BDA/06w_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas

##다양한 데이터 프레임 생성

In [ ]:
import pandas as pd

# 방법 1
courses = pd.Series(["Spark", "PySpark", "Hadoop"], name="courses")
fees = pd.Series([250000, 300000, 200000], name="fees")

df1 = pd.DataFrame([courses, fees])
print(df1)
print()

print(df1.T)
print()

# 방법 2
df2 = pd.DataFrame()

df2[courses.name] = courses
df2[fees.name] = fees

print(df2)

              0        1       2
courses   Spark  PySpark  Hadoop
fees     250000   300000  200000

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

In [ ]:
#여러 dict의 목록 데이터 사용
import pandas as pd

df1 = pd.DataFrame([
    {'국어': 70, '수학': 89, '영어': 90},
    {'국어': 80, '영어': 99},
    {'수학': 66, '영어': 78}
])
print(df1)
print()

s1 = pd.Series([90, 80, 60, 66])
s2 = pd.Series([45, 73, 83, 99])
s3 = pd.Series([92, 75, 82, 75])

df = pd.DataFrame({'국어': s1, '영어': s2, '수학': s3})
print(df)
print()

df.index = ['노', '장', '박', '강']
print(df)

     국어    수학  영어
0  70.0  89.0  90
1  80.0   NaN  99
2   NaN  66.0  78

   국어  영어  수학
0  90  45  92
1  80  73  75
2  60  83  82
3  66  99  75

   국어  영어  수학
노  90  45  92
장  80  73  75
박  60  83  82
강  66  99  75

In [ ]:
#데이터프레임의 결측값 표시 NaN
import pandas as pd

df1 = pd.DataFrame({
    'A': pd.Series([10, 20, 30], index=[0, 1, 2]),
    'B': pd.Series([3, 2, 1], index=[1, 2, 3])
})
print(df1)
print()

s1 = pd.Series([90, 80, 60], index=['노', '장', '박'])
s2 = pd.Series([45, 73, 99], index=['장', '박', '강'])
s3 = pd.Series([92, 75, 82, 75])

df2 = pd.DataFrame({'국어': s1, '영어': s2, '수학': s3},
                   index=['노', '장', '박', '강'])
print(df2)

      A    B
0  10.0  NaN
1  20.0  3.0
2  30.0  2.0
3   NaN  1.0

     국어    영어  수학
노  90.0   NaN NaN
장  80.0  45.0 NaN
박  60.0  73.0 NaN
강   NaN  99.0 NaN

In [ ]:
#df.dtypes
import pandas as pd
import numpy as np

d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
print(df)
print()

print(df.dtypes)
print()

df = pd.DataFrame(data=d, dtype=np.int8)
print(df.dtypes)

   col1  col2
0     1     3
1     2     4

col1    int64
col2    int64
dtype: object

col1    int8
col2    int8
dtype: object

###날짜

In [ ]:
#여러 날짜 시퀀스를 위한 함수 date_range()
import pandas as pd

dates = pd.date_range("20250101", periods=6)
print(dates)
print()

print(dates[0])
print()

dates = pd.date_range("20250101", end="20250110")
print(dates)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06'],
              dtype='datetime64[ns]', freq='D')

2025-01-01 00:00:00

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
import pandas as pd

dates = pd.date_range("20250101", periods=6, freq='3D')
print(dates)
print()

dates = pd.date_range("20250101", periods=6, freq='3H')
print(dates)
print()

dates = pd.date_range("20250101", periods=6, freq='W')
print(dates)
print()

dates = pd.date_range("20260101", periods=6, freq='W-SUN')
print(dates)

DatetimeIndex(['2025-01-01', '2025-01-04', '2025-01-07', '2025-01-10',
               '2025-01-13', '2025-01-16'],
              dtype='datetime64[ns]', freq='3D')

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 03:00:00',
               '2025-01-01 06:00:00', '2025-01-01 09:00:00',
               '2025-01-01 12:00:00', '2025-01-01 15:00:00'],
              dtype='datetime64[ns]', freq='3h')

DatetimeIndex(['2025-01-05', '2025-01-12', '2025-01-19', '2025-01-26',
               '2025-02-02', '2025-02-09'],
              dtype='datetime64[ns]', freq='W-SUN')

DatetimeIndex(['2026-01-04', '2026-01-11', '2026-01-18', '2026-01-25',
               '2026-02-01', '2026-02-08'],
              dtype='datetime64[ns]', freq='W-SUN')

/tmp/ipykernel_43540/4204082110.py:7: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range("20250101", periods=6, freq='3H')

In [ ]:
import pandas as pd

dates = pd.date_range("20260101", periods=6, freq='W-TUE')
print(dates)
print()

dates = pd.date_range("20260101", periods=6, freq='W-FRI')
print(dates)
print()

dates = pd.date_range("20250101", periods=6, freq='M')
print(dates)
print()

dates = pd.date_range("20250101", periods=6, freq='MS')
print(dates)

DatetimeIndex(['2026-01-06', '2026-01-13', '2026-01-20', '2026-01-27',
               '2026-02-03', '2026-02-10'],
              dtype='datetime64[ns]', freq='W-TUE')

DatetimeIndex(['2026-01-02', '2026-01-09', '2026-01-16', '2026-01-23',
               '2026-01-30', '2026-02-06'],
              dtype='datetime64[ns]', freq='W-FRI')

DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30'],
              dtype='datetime64[ns]', freq='ME')

DatetimeIndex(['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01'],
              dtype='datetime64[ns]', freq='MS')

/tmp/ipykernel_43540/1366026118.py:11: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range("20250101", periods=6, freq='M')

In [ ]:
#날짜 DataFrame
import pandas as pd
import numpy as np

dates = pd.date_range("20250302", periods=6)
print(dates)
print()

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
print(df)

DatetimeIndex(['2025-03-02', '2025-03-03', '2025-03-04', '2025-03-05',
               '2025-03-06', '2025-03-07'],
              dtype='datetime64[ns]', freq='D')

                   A         B         C         D
2025-03-02  0.394411  0.927684 -0.076062 -0.234534
2025-03-03 -1.240460 -0.478548  0.857827 -0.603100
2025-03-04 -1.271547 -0.685608  1.543826  1.228403
2025-03-05 -1.346620 -0.108427 -0.348454  0.703990
2025-03-06  0.546060 -0.798696  0.930258 -0.748399
2025-03-07 -0.321763  0.083175 -0.624690  1.080553

In [ ]:
import pandas as pd
import numpy as np

df2 = pd.DataFrame({
    "A": 1.0,
    "B": pd.Timestamp("20260302"),
    "C": pd.Series(np.arange(1, 3, .5)),
    "D": np.array([3] * 4, dtype="int32"),
    "E": pd.Categorical(["test", "train", "test", "train"]),
    "F": "foo"
})

print(df2)
print()

print(df2.dtypes)

     A          B    C  D      E    F
0  1.0 2026-03-02  1.0  3   test  foo
1  1.0 2026-03-02  1.5  3  train  foo
2  1.0 2026-03-02  2.0  3   test  foo
3  1.0 2026-03-02  2.5  3  train  foo

A          float64
B    datetime64[s]
C          float64
D            int32
E         category
F           object
dtype: object

##DataFrame의 다양한 참조

In [ ]:
#열 참조
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)

print(pf)
print()

print(pf['중간'])
print()

print(pf.중간)
print()

print(pf['출석'])
print()

print(pf[['출석']])
print()

print(pf[['기말', '출석', '중간']])
print()

print(pf[['기말']])

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

윤일형    18
강수희    20
홍소희    19
유한빈    20
신수빈    16
Name: 출석, dtype: int64

     출석
윤일형  18
강수희  20
홍소희  19
유한빈  20
신수빈  16

     기말  출석  중간
윤일형  35  18  25
강수희  27  20  18
홍소희  17  19  17
유한빈  22  20  12
신수빈  34  16  22

     기말
윤일형  35
강수희  27
홍소희  17
유한빈  22
신수빈  34

In [ ]:
#행 참조
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)

print(pf)
print()

print(pf['중간'] > 20)
print()

print(pf[pf['중간'] > 20])
print()

print(pf[pf['출석'] >= 19])
print()

print(pf[(pf['출석'] >= 19) & (pf['기말'] >= 20)])

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

윤일형     True
강수희    False
홍소희    False
유한빈    False
신수빈     True
Name: 중간, dtype: bool

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [ ]:
#loc
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)

print(pf)
print()

print(pf.loc['윤일형'])
print()

print(pf.loc[['윤일형']])
print()

print(pf.loc[['홍소희', '윤일형']])
print()

print(pf.loc['윤일형':'유한빈'])
print()

print(pf.loc[pf.중간 > 20])
print()

print(pf.loc[(pf.중간 > 10) & (pf.과제 == 10)])

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

     중간  기말  과제  출석
윤일형  25  35   8  18

     중간  기말  과제  출석
홍소희  17  17  10  19
윤일형  25  35   8  18

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19

In [ ]:
#index 행 참조
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)

print(pf)
print()

print(pf.loc[pf.index[0]])
print()

print(pf.loc[[pf.index[0]]])
print()

print(pf.loc[pf.index[1:4]])
print()

print(pf.loc[pf.index[1:4]][['기말', '과제']])

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

     중간  기말  과제  출석
윤일형  25  35   8  18

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

     기말  과제
강수희  27  10
홍소희  17  10
유한빈  22   9

In [ ]:
#loc 열 참조
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)

print(pf)
print()

print(pf.loc[:, '과제'])
print()

print(pf.loc[:, '중간':'과제'])
print()

print(pf.loc[:, ['기말', '출석']])

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

     중간  기말  과제
윤일형  25  35   8
강수희  18  27  10
홍소희  17  17  10
유한빈  12  22   9
신수빈  22  34   8

     기말  출석
윤일형  35  18
강수희  27  20
홍소희  17  19
유한빈  22  20
신수빈  34  16

In [ ]:
#loc columns 열 참조
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)

print(pf)
print()

print(pf.loc[:, pf.columns[0]])
print()

print(pf.loc[:, [pf.columns[0]]])
print()

print(pf.loc[:, pf.columns[1:]])
print()

print(pf.loc[:, pf.columns[1:]][['기말', '과제']])

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

     중간
윤일형  25
강수희  18
홍소희  17
유한빈  12
신수빈  22

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [ ]:
#행과 열 참조
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)

print(pf)
print()

print(pf.loc['윤일형', '출석'])
print()

print(pf.loc['윤일형':'유한빈', '기말'])
print()

print(pf.loc['윤일형':'유한빈', '기말':'과제'])   #앞 뒤 둘다 : 이면 DataFrame으로 결과 나
print()

print(pf.loc[pf.index[0], pf.columns[1]])
print()

print(pf.loc[pf.index[0:3], pf.columns[2]])
print()

print(pf.loc[pf.index[0:3], pf.columns[2:]])

In [ ]:
#df.iloc[정수] 참조
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)

print(pf)
print()

print(pf.iloc[1])
print()

print(pf.iloc[[1]])
print()

print(pf.iloc[[1, 3]])
print()

print(pf.iloc[2:])

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

중간    18
기말    27
과제    10
출석    20
Name: 강수희, dtype: int64

     중간  기말  과제  출석
강수희  18  27  10  20

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

     중간  기말  과제  출석
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
#df.iloc[:, 정수] 참조
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)

print(pf)
print()

print(pf.iloc[:, 2])
print()

print(pf.iloc[:, [2]]) #앞 뒤 둘중에 리스트로 한 번더 덮으면 데이터 프레임
print()

print(pf.iloc[:, 1:])

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

     과제
윤일형   8
강수희  10
홍소희  10
유한빈   9
신수빈   8

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [ ]:
#df.iloc[행번호, 열번호] 참조

import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)

print(pf)
print()

print(pf.iloc[1, 1])
print()

print(pf.iloc[1:3, 1:])
print()

print(pf.iloc[:, 1:])
print()

print(pf.iloc[[1, 3, 4], 1:])
print()

print(pf.iloc[[1, 3, 4], [0, 1]])

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

27

     기말  과제  출석
강수희  27  10  20
홍소희  17  10  19

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

     기말  과제  출석
강수희  27  10  20
유한빈  22   9  20
신수빈  34   8  16

     중간  기말
강수희  18  27
유한빈  12  22
신수빈  22  34

In [ ]:
#at['행명', '열명'] 참조 쓰는 이유는 이렇게 쓰면 빠르다고 해서 그렇다함...
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)

print(pf)
print()

print(pf.at['윤일형', '과제'])
print()

print(pf.at['유한빈', '기말'])
print()

print(pf.at[pf.index[1], '출석'])
print()

print(pf.at[pf.index[3], pf.columns[2]])

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

8

22

20

9

In [ ]:
#iat
import pandas as pd

pf = pd.DataFrame(
    data=[[25, 35, 8, 18],
          [18, 27, 10, 20],
          [17, 17, 10, 19],
          [12, 22, 9, 20],
          [22, 34, 8, 16]],
    index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
    columns=['중간', '기말', '과제', '출석']
)

print(pf)
print()

print(pf.iat[1, 2])
print()

print(pf.iat[2, 3])

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

10

19

#실습 겸 내가 바꾸고 싶은 것

In [ ]:
import pandas as pd
pf = pd.DataFrame(data = [[22, 57, 6, 12],
                          [16, 23, 8, 1],
                          [83, 23, 15, 72],
                          [12, 15, 17, 21],
                          [21, 23, 51, 32]],
                  index = ["윤현빈", "오지민", "박세진", "김정빈", "송호진"],
                  columns = ["중간", "기말", "과제", "출석"])
pf

     중간  기말  과제  출석
윤현빈  22  57   6  12
오지민  16  23   8   1
박세진  83  23  15  72
김정빈  12  15  17  21
송호진  21  23  51  32

In [ ]:
pf["중간"]

윤현빈    22
오지민    16
박세진    83
김정빈    12
송호진    21
Name: 중간, dtype: int64

In [ ]:
pf.중간

윤현빈    22
오지민    16
박세진    83
김정빈    12
송호진    21
Name: 중간, dtype: int64

In [ ]:
pf[["중간", "기말"]]

     중간  기말
윤현빈  22  57
오지민  16  23
박세진  83  23
김정빈  12  15
송호진  21  23

In [ ]:
pf[["기말"]]

     기말
윤현빈  57
오지민  23
박세진  23
김정빈  15
송호진  23

In [ ]:
pf[pf["중간"] > 20]

     중간  기말  과제  출석
윤현빈  22  57   6  12
박세진  83  23  15  72
송호진  21  23  51  32

In [ ]:
pf.loc["윤현빈"]

중간    22
기말    57
과제     6
출석    12
Name: 윤현빈, dtype: int64

In [ ]:
pf.loc[:, "기말"]

윤현빈    57
오지민    23
박세진    23
김정빈    15
송호진    23
Name: 기말, dtype: int64

In [ ]:
pf.loc[pf.중간 > 20]

     중간  기말  과제  출석
윤현빈  22  57   6  12
박세진  83  23  15  72
송호진  21  23  51  32

In [ ]:
pf.loc[(pf.중간 > 20) & (pf.기말 > 15)]

     중간  기말  과제  출석
윤현빈  22  57   6  12
박세진  83  23  15  72
송호진  21  23  51  32

In [ ]:
pf.loc[pf.index[1]]

중간    16
기말    23
과제     8
출석     1
Name: 오지민, dtype: int64

In [ ]:
pf.loc[:, "중간":"출석"]

     중간  기말  과제  출석
윤현빈  22  57   6  12
오지민  16  23   8   1
박세진  83  23  15  72
김정빈  12  15  17  21
송호진  21  23  51  32

In [ ]:
pf.iloc[[1, 3], 1:3]

     기말  과제
오지민  23   8
김정빈  15  17

In [ ]:
pf.iloc[1, 1]

np.int64(23)

In [ ]:
pf.iloc[1:3, 1:3]

     기말  과제
오지민  23   8
박세진  23  15

In [ ]:
pf.iloc[[0, 2, 4], [0, 2, 3]]

     중간  과제  출석
윤현빈  22   6  12
박세진  83  15  72
송호진  21  51  32